FROM python:3

RUN pip install --upgrade pip
RUN pip install boto3
RUN pip install boto
RUN pip install Flask
RUN pip install pandas
RUN pip install beautifulsoup4
RUN pip install urllib3
Run pip install requests
Run pip install lxml
RUN pip install html5lib


COPY p2.py /p2.py
CMD [ "python", "./p2.py"]
